---
title: Test basic functionalities of scGate on human data
author: 
- Massimo Andreatta^[massimo.andreatta@unil.ch]
- Ariel Berenstein^[aberenstein@conicet.gov.ar]
- Santiago Carmona^[santiago.carmona@unil.ch]
date: "15/02/2021"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
#output: html_notebook
---



```{r, message=F, warning=F,results=F}
library(renv)
renv::activate()
renv::restore()
```

```{r message=F, warning=F}
library(ggplot2)
library(scGate)
library(SingleR)
library(dplyr)
library(BiocParallel)
library(patchwork)
library(parallel)
library(Seurat)
```



# Get some testing datasets
```{r}
ddir <- "./aux"
dir.create(ddir, showWarnings = FALSE)
options(timeout=1000)
if(TRUE){
  #subset 50K Hao et.al. 2021
  rds.file <- paste0(ddir,"/Hao_subset50K_sct.rds")
  if (!file.exists(rds.file)) {
    dataUrl <- "https://figshare.com/ndownloader/files/31347367?private_link=31c57715c30ce9f57552"
    download.file(dataUrl, rds.file)
  }
  pbmc.azimuth.subset <- readRDS(rds.file)
  
}else{
  # Hao_subset50K_sct.rds was generated in this way:
  dataUrl <- "https://atlas.fredhutch.org/data/nygc/multimodal/pbmc_multimodal.h5seurat"
  dset.h5 <- sprintf("%s/pbmc_multimodal.h5seurat", ddir)
  if (!file.exists(dset.h5)) {
     download.file(dataUrl, dset.file)
  }
  pbmc.azimuth.full <- SeuratDisk::LoadH5Seurat(dset.h5)
  pbmc.azimuth.full <- DietSeurat(pbmc.azimuth.full, counts = T, scale.data = FALSE, assays = 'SCT',dimreducs = NULL)
  pbmc.azimuth.subset <- subset(pbmc.azimuth.full, cells=sample(Cells(pbmc.azimuth.full),50000))
  saveRDS(pbmc.azimuth.subset,file = paste0(ddir,"/Hao_subset50K_sct.rds"))
}

#Reduce object size
pbmc.azimuth.subset@assays$RNA <- pbmc.azimuth.subset@assays$SCT
DefaultAssay(pbmc.azimuth.subset) <- "RNA"
class(pbmc.azimuth.subset@assays$RNA) <- 'Assay'
pbmc.azimuth.subset@assays$SCT <- NULL

gc(reset=T)
```

## Load scGate models
```{r}
models.DB <- scGate::get_scGateDB(version="v0.4")
model <- models.DB$human$generic$CD8T  # model with 4 levels 
model$levels%>%unique()%>%length()
```

# Set parameters for time comparison
```{r}
timing <- list()
ncells <- c(500,1000,5000,10000,25000,50000)
#ncells <- c(500,1000,5000,10000,25000)
NC <- 4
```

### Load training data for SIngleR
```{r}
hpca.se <- HumanPrimaryCellAtlasData()  ## reference
param <- MulticoreParam(workers = NC)    # configure parallelization
```



# subset testing dataset (with different number of cells)  and run both models
```{r}
for(downsample in ncells){
  for(i in c("a","b","c")){  # each point will be ran 3 times. 
    # subset dataset
    subseted.obj <- subset(pbmc.azimuth.subset, cells=sample(Cells(pbmc.azimuth.subset),downsample))
    gc()
    message(sprintf("runing methods with %s cells; iter %s",downsample,i))
    #scGate
    t0 <- Sys.time()
    scGate(subseted.obj, model = model, ncores = NC)
    t1 <- Sys.time() 
    tt <- t1-t0
    deltaT <- as.numeric(tt, units = "mins")
    #reserve result
    timing[[paste0("Ncell_",downsample)]][["scGate"]][[i]] <- deltaT
  }
}
gc(reset = T)
```


```{r}
#### SIngleR
for(downsample in ncells){
  for(i in c("a","b","c")){
    # subset dataset
    subseted.obj <- subset(pbmc.azimuth.subset, cells=sample(Cells(pbmc.azimuth.subset),downsample))
    gc()
    message(sprintf("runing methods with %s cells; iter %s",downsample,i))
    t0 <- Sys.time()
    SingleR(test = GetAssayData(subseted.obj), ref = hpca.se, labels = hpca.se$label.fine, BPPARAM=param)
    t1 <- Sys.time() 
    tt <- t1-t0
    deltaT <- as.numeric(tt, units = "mins")
    #reserve result
    timing[[paste0("Ncell_",downsample)]][["SingleR"]][[i]] <-  deltaT 
  }
}
```


```{r}
results <- list(timing = timing)
saveRDS(results,paste0(ddir,"/runtime_SingleR_scGate_4core.rds"))


```

```{r}
res.time <- data.frame()

for(mtd in c("SingleR","scGate")){
  for(nc in ncells){
    xx <- unlist(results$timing[[paste0("Ncell_",nc)]][[mtd]])
    a <- mean(xx,na.rm =T)
    if(is.null(a)){a <- NA}
    res.time <- rbind(res.time,data.frame("Ncell"= nc,method = mtd,time = a))
  }
}

```


```{r,fig.width = 10,fig.height = 5}
plt.time <- ggplot(res.time,aes(x=Ncell,y = time,
               group =method, colour = method)) + geom_line() + ylab("Time [min]")  + xlab("# cells") + geom_point() + theme_bw() + theme(axis.text.x = element_text(angle = 60,hjust=1), legend.position = "none") 


plt <- plt.time 
save = FALSE
if(save){
  ggsave(filename = paste0(ddir,"/runtime_benchmark_onDocker_4c.png"),plot = plt, width = 7,height = 7)
  ggsave(filename = paste0(ddir,"/runtime_benchmark_onDocker_4c.pdf"),plot = plt, width = 7,height = 7)
}
```


