---
title: "Small benchmark of cell type isolation with scGate and other methods"
author: "M. Andreatta, A. Berenstein and S. Carmona"
date: "29/09/2021"
output:
  rmdformats::readthedown:
    self-contained: true
    highlight: haddock
    thumbnails: false
    css: styles.css
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file, encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'scGate.bench.html'))})
---


```{r, message=F, warning=F,results=F}
library(renv)
renv::activate()
renv::restore()
#remotes::install_github("carmonalab/UCell", ref="v1.1")
#remotes::install_github("mojaveazure/seurat-disk",ref="163f1aade5bac38ed1e9e9c912283a7e74781610")
#remotes::install_github("carmonalab/scGate", ref='v1.0.0') #stable release
#install.packages("SCINA")

library(ggplot2)
library(dplyr)
library(scGate)
library(SingleR)
library(SCINA)
```

## Load some testing datasets and models

Load datasets (you will need ~ 14gb of RAM)
```{r}
rds.file = "./aux/human_sets_benchmark.rds"
if (!file.exists(rds.file)) {
  options(timeout=2000)
  download.file("https://figshare.com/ndownloader/files/31346815?private_link=7d4d9376a3bbdb17bc00", rds.file)
}
testing.datasets <- readRDS(rds.file) 

ground_truth_categories <- readRDS("./aux/SingleR_goldStandard.rds")  #Load an object containing stardard cell type annotations - to allow comparing different methods

figure.path <- "./plots/"
dir.create(figure.path)

```

Load default models from DB
```{r}
models.DB <- scGate::get_scGateDB(version="v0.4")  ### NB: force update will make results non-reproducible. We must specify a tag for download, or alternatively include the set of models in the repo

models <- models.DB$human$generic  ## Pre-compiled list of models for human cell types
print(models%>%names)

```


## Run models and compute performance

```{r}
## SingleR
library(celldex)
hpca.se <- HumanPrimaryCellAtlasData() 
param <- BiocParallel::MulticoreParam(workers = 4)

dset.to.run <- names(testing.datasets)
res.SingleR <- list()
SingleR.output <- list()
for(dset in dset.to.run){
    obj <- testing.datasets[[dset]]
    SingleR.output[[dset]] <- SingleR(test = GetAssayData(obj), ref = hpca.se,labels = hpca.se$label.fine, BPPARAM=param)
    res.SingleR[[dset]][["SingleR.fine"]] <- SingleR.output[[dset]]$pruned.labels
}
```


Run scGate
```{r,collapse =T, results= F, echo = F}
# List available testing datasets:
names(testing.datasets)

results <- data.frame()
models <- models[names(models)!="Tcell.alphabeta"] #skip this model since there is no equivalent class in hpca for SingleR

for(dset in dset.to.run){
  message(sprintf('-Running %s',dset))
  obj <- testing.datasets[[dset]]
  assay <-  DefaultAssay(obj)
  

  for(model.name in names(models)){
    message(sprintf('---Running %s',model.name))
    model <- models[[model.name]]
    obj <- scGate(data = obj, model = model, ncores = 4, keep.ranks = TRUE, output.col.name = paste0('is.pure.',model.name), assay = assay)
    
    res <- scGate::performance.metrics(actual = obj@meta.data[,model.name], pred = obj@meta.data[,paste0("is.pure.",model.name)] == "Pure")
    res <- data.frame(value = res, metric = names(res),model = model.name,dataset = dset,method = "scGate")
    results <- rbind(results,res)
    
    #merge SingleR results
    pred.singleR <- (res.SingleR[[dset]])$SingleR.fine%>%grepl(ground_truth_categories$hpca_categories[[model.name]],.)+0
    singleR <- scGate::performance.metrics(actual = obj@meta.data[,model.name], pred = pred.singleR == 1)
    singleR <- data.frame(value = singleR, metric = names(singleR),model = model.name,dataset = dset,method = 'SingleR')
    results <- rbind(results,singleR)
  }

}
```

# Build SCINA model signatures 
```{r}
scina.signatures <- list()
scina.signatures$Bcell <- c("MS4A1","BANK1","PAX5","CD19","CD79A") 
#scina.signatures$Plasma <- c("IGKC","IGHG3","IGHG1","IGHA1","CD79A") 
scina.signatures$PanBcell <- c("CD79A")

scina.signatures$MoMacDC<- c("SPI1","CD40","CD68","CD14","FCGR1A","LYZ","CSF1R","MSR1","MAFB","CD300E")
scina.signatures$Myeloid<- c("SPI1","CD40","CD68","CD14","FCGR1A","LYZ","CSF1R","MSR1","MAFB","CD300E","CSF3R","FCGR3B")

scina.signatures$Tcell <- c("CD3D","CD3E","CD3G","CD2")

scina.signatures$CD4T <- c("CD3D","CD3E","CD3G","CD2","CD4","CD40LG","FOXP3")
scina.signatures$CD8T <- c("CD3D","CD3E","CD3G","CD2","CD8A","CD8B")
scina.signatures$NK<- c("LCK","KLRD1","NKG7","NCR1","FCGR3A")
```

# Run SCINA
```{r}
for(dset in dset.to.run){
  message(sprintf('-Running %s',dset))
  obj <- testing.datasets[[dset]]
  assay <-  DefaultAssay(obj)
  expr.mat <- GetAssayData(object = obj,assay = assay)
  res.scina <- SCINA(expr.mat,signatures = scina.signatures, max_iter=100,convergence_n=10,convergence_rate=0.99,sensitivity_cutoff=0.9,rm_overlap=F)

  for(model.name in names(models)){
    pred.SCINA <- (res.scina$cell_labels==model.name) + 0
    res.SCINA <- scGate::performance.metrics(actual = obj@meta.data[,model.name], pred = pred.SCINA == 1)
    res.SCINA <- data.frame(value = res.SCINA, metric = names(res.SCINA),model = model.name,dataset = dset,method = 'SCINA')
    results <- rbind(results,res.SCINA)
  }  
}
```

Summarize performance
```{r,fig.width = 8,fig.height=5}
data_summary <- function(x) {
     m <- mean(x)
     se <- function(x) sqrt(var(x)/length(x))
     ymin <- m-se(x)
     ymax <- m+se(x)
     return(c(y=m,ymin=ymin,ymax=ymax))
}
  
res <- results%>%subset(metric %in% c("PREC","MCC") & model!= "Plasma_cell")
  
  
res.prec <- res%>%subset(metric == "PREC")
res.mcc <- res%>%subset(metric == "MCC")
```


And visualize performance metrics in one plot
```{r}
colors <- c("#E69F00", "#56B4E9","#56E9BA")

res.prec <- res.prec[!is.na(res.prec$value),]
res.prec$model <- factor(res.prec$model, levels=c("Bcell","PanBcell","MoMacDC","Myeloid","NK","Tcell","CD4T","CD8T"))   #reorder in more intuitive way

smm.prec <- aggregate(res.prec$value, list(res.prec$method, res.prec$model), FUN=mean)
colnames(smm.prec) <- c("method","model","value")

plt.prec <- ggplot() +
  geom_bar(data=smm.prec, aes(x=model, y=value, fill=method), stat="identity", position="dodge", width = 0.75, alpha=0.3) +
  geom_jitter(data=res.prec, aes(x=model, y=value, color = method, shape = dataset), 
              position=position_jitterdodge(jitter.width = 0.1), size = 2) +
  scale_color_manual(values=colors) + scale_fill_manual(values=colors) +
  ylab("Precision")   + theme_bw() + theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 60, vjust = 0.4, hjust=0.5)) 
  

res.mcc <- res.mcc[!is.na(res.mcc$value),]
res.mcc$model <- factor(res.mcc$model, levels=c("Bcell","PanBcell","MoMacDC","Myeloid","NK","Tcell","CD4T","CD8T"))   #reorder in more intuitive way

smm.mcc <- aggregate(res.mcc$value, list(res.mcc$method, res.mcc$model), FUN=mean)
colnames(smm.mcc) <- c("method","model","value")


plt.mcc <- ggplot() +
  geom_bar(data=smm.mcc, aes(x=model, y=value, fill=method), stat="identity", position="dodge", width = 0.75, alpha=0.3) +
  geom_jitter(data=res.mcc, aes(x=model, y=value, color = method, shape = dataset), 
              position=position_jitterdodge(jitter.width = 0.1), size = 2) +
  scale_color_manual(values=colors) + scale_fill_manual(values=colors) +
  ylab("MCC")   + theme_bw() +
  theme(axis.text.x = element_text(angle = 60, vjust = 0.4, hjust=0.5)) 

a <- plt.prec | plt.mcc
b <- plt.prec / plt.mcc

a

ggsave(file.path(figure.path,"benchmark_15012022_scGate_lands.pdf"), plot=a, width=9, height=4)

#remove x axis labels
plt.prec <- plt.prec + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

b <- plt.prec / plt.mcc
b

ggsave(file.path(figure.path,"benchmark_15012022_scGate_portr.pdf"), plot=b, width=6, height=4)

```

```{r,echo =FALSE, results=F}
saveRDS(results,file = file.path(figure.path,"benchmark_15012022_scGate.rds")) 
```


