---
title: Test basic functionalities of scGate on human data
author: 
- Massimo Andreatta^[massimo.andreatta@unil.ch]
- Ariel Berenstein^[aberenstein@conicet.gov.ar]
- Santiago Carmona^[santiago.carmona@unil.ch]
date: "15/02/2021"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
#output: html_notebook
---


```{r message=F, warning=F}
library(ggplot2)
library(scGate)
library(SingleR)
library(dplyr)
library(BiocParallel)
library(patchwork)
library(parallel)
#install.packages("Seurat")
#library(Seurat)
```



# Get some testing datasets
```{r}
#BiocManager::install(c("cli","crayon","hdf5r","Matrix","R6","rlang","SeuratObject","stringi","withr"))
#remotes::install_github("mojaveazure/seurat-disk")
#testing.datasets <- scGate:::get_testing_data(version = 'hsa.latest')
ddir <- "~/Datasets/"
dir.create(ddir, showWarnings = FALSE)
options(timeout=1000)
dataUrl <- "https://atlas.fredhutch.org/data/nygc/multimodal/pbmc_multimodal.h5seurat"

dset.h5 <- sprintf("%s/pbmc_multimodal.h5seurat", ddir)
if (!file.exists(dset.h5)) {
   download.file(dataUrl, dset.file)
}
pbmc.azimuth.full <- SeuratDisk::LoadH5Seurat(dset.h5)

#Reduce object size
pbmc.azimuth.full <- DietSeurat(pbmc.azimuth.full, counts = T, scale.data = FALSE, assays = 'SCT',dimreducs = NULL)

pbmc.azimuth.full@assays$RNA <- pbmc.azimuth.full@assays$SCT
DefaultAssay(pbmc.azimuth.full) <- "RNA"
class(pbmc.azimuth.full@assays$RNA) <- 'Assay'

pbmc.azimuth.full@assays$SCT <- NULL
gc(reset=T)
```

## Load scGate models
```{r}
models.DB <- scGate::get_scGateDB()
model <- models.DB$human$generic$CD8T  # model with 4 levels 
model$levels%>%unique()%>%length()
```

# Set parameters for time comparison
```{r}
timing <- list()
memory <- list()
#ncells <- c(500,1000,5000,10000,25000,50000,100000)
ncells <- c(500,1000,5000,10000,25000)
```

### Load training data for SIngleR
```{r}
hpca.se <- HumanPrimaryCellAtlasData()  ## reference
#param <- MulticoreParam(workers = 4)    # configure parallelization
```



# subset testing dataset (with different number of cells)  and run both models
```{r}
for(downsample in ncells){
  for(i in c("a","b","c")){
    # subset dataset
    subseted.obj <- subset(pbmc.azimuth.full, cells=sample(Cells(pbmc.azimuth.full),downsample))
    gc()
    message(sprintf("runing methods with %s cells; iter %s",downsample,i))
    #scGate
    gc1 <- gc(reset = TRUE)
    t0 <- Sys.time()
    out <- tryCatch({
            scGate(subseted.obj, model = model, ncores = 1)
        },
      error=function(cond) {
        message(cond)
        return(NA)
    })
    t1 <- Sys.time() 
    tt <- t1-t0
    deltaT <- as.numeric(tt, units = "mins")
    gc2 <- gc()
    if (is.na(out)) { #Out of memory
      memPeak <- NA
      time <- NA
    } else {
      memPeak <- (sum(gc2[,7]) - sum(gc1[,7]))/1000
      time <- deltaT
    }
    #reserve result
    timing[[paste0("Ncell_",downsample)]][["scGate"]][[i]] <- time
    memory[[paste0("Ncell_",downsample)]][["scGate"]][[i]] <- memPeak 
  }
}
gc(reset = T)
```


```{r}
#### SIngleR
for(downsample in ncells){
  for(i in c("a","b","c")){
    # subset dataset
    subseted.obj <- subset(pbmc.azimuth.full, cells=sample(Cells(pbmc.azimuth.full),downsample))
    gc()
    message(sprintf("runing methods with %s cells; iter %s",downsample,i))
    gc1 <- gc(reset = TRUE)
    t0 <- Sys.time()
    out <- tryCatch({
 #      SingleR(test = GetAssayData(subseted.obj), ref = hpca.se, labels = hpca.se$label.fine, BPPARAM=param)
        SingleR(test = GetAssayData(subseted.obj), ref = hpca.se, labels = hpca.se$label.fine)
        },
      error=function(cond) {
        message(cond)
        return(NA)
    })
    t1 <- Sys.time() 
    tt <- t1-t0
    deltaT <- as.numeric(tt, units = "mins")
    gc2 <- gc()
    if (is.na(out)) { #Out of memory
      memPeak <- NA
      time <- NA
    } else {
      memPeak <- (sum(gc2[,7]) - sum(gc1[,7]))/1000
      time <- deltaT
    }
    
  
    #reserve result
    timing[[paste0("Ncell_",downsample)]][["SingleR"]][[i]] <-  deltaT 
    memory[[paste0("Ncell_",downsample)]][["SingleR"]][[i]] <- memPeak 
  }
}
```


```{r}
results <- list(timing = timing, memory = memory)
saveRDS(results,"time_memory_SingleR_scGate_1core_MACOSX.rds")
#saveRDS(results,"/home/rstudio/Figures/time_memory_SingleR_scGate_1core_MACOSX.rds")

```

```{r}
res.time <- data.frame()

for(mtd in c("SingleR","scGate")){
  for(nc in ncells){
    xx <- unlist(results$timing[[paste0("Ncell_",nc)]][[mtd]])
    a <- mean(xx,na.rm =T)
    if(is.null(a)){a <- NA}
    res.time <- rbind(res.time,data.frame("Ncell"= nc,method = mtd,time = a))
  }
}

res.memory <- data.frame()

for(mtd in c("SingleR","scGate")){
  for(nc in ncells){
    xx <- unlist(results$memory[[paste0("Ncell_",nc)]][[mtd]])
    a <- mean(xx,na.rm =T)
    if(is.null(a)){a <- NA}
    res.memory <- rbind(res.memory,data.frame("Ncell"= nc,method = mtd,memory = a))
  }
}



```


```{r,fig.width = 10,fig.height = 5}
plt.time <- ggplot(res.time,aes(x=Ncell,y = time,
               group =method, colour = method)) + geom_line() + ylab("Time [min]")  + xlab("# cells") + geom_point() + theme_bw() + theme(axis.text.x = element_text(angle = 60,hjust=1), legend.position = "none") 

plt.mem <- ggplot(res.memory,aes(x=Ncell,y = memory,
               group =method, colour = method)) + geom_line() + ylab("Memory [Gb]")  + xlab("# cells") + geom_point() + theme_bw() + theme(axis.text.x = element_text(angle = 60,hjust=1))

plt <- plt.time + plt.mem
plt
#ggsave(filename = "~/Figures/time_memory_benchmark_docker_4c_16gb_IntelI5.pdf",plot = plt,width = 10,height = 5)
#ggsave(filename = "~/Figures/time_memory_benchmark_docker_4c_16gb_IntelI5.png",plot = plt,width = 10,height = 5)
ggsave(filename = "time_memory_benchmark_docker_1c.png",plot = plt,width = 10,height = 5)

```


